---
- hosts: all
  become: yes
  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
  tasks:
    # Install apt dependencies
    - name: install dependencies
      apt: name={{ item }}
      with_items:
        - python
        - apache2
        - apache2-utils
        - python-pip
        - python-yaml
      notify:
        - restart apache2
    - name: install python dependencies
      pip: name={{ item }}
      with_items:
        - requests
        - python-firebase

    # Enable apache mods
    - name: enable apache mods
      apache2_module: state=present name={{ item }}
      with_items:
        - cgid
        - ssl
      notify:
        - restart apache2

    # Setup vhost
    - name: copy webapp vhost conf
      template: src=conf/apache.conf dest=/etc/apache2/sites-available/{{fqdn}}.conf
    - name: enable site
      command: a2ensite {{fqdn}}.conf
      args:
        creates: /etc/apache2/sites-enabled/{{fqdn}}.conf
      notify:
        - restart apache2

    # Copy SSL cert
    - name: make ssl dir
      file: path=/etc/apache2/ssl state=directory mode=755 owner=root group=root
    - name: copy webapp ssl cert
      copy: src=ssl/{{fqdn}}.crt dest=/etc/apache2/ssl/{{fqdn}}.crt owner=root group=root
    - name: copy webapp ssl key
      copy: src=ssl/{{fqdn}}.key dest=/etc/apache2/ssl/{{fqdn}}.key owner=root group=root

    # Copy webapp
    - name: copy webapp
      copy: src=webapp/ dest=/var/www/{{fqdn}} owner=www-data group=www-data
    - name: make cgi executable
      file: path={{item}} mode="a+x"
      with_items:
        - /var/www/{{fqdn}}/log.cgi
        - /var/www/{{fqdn}}/report.cgi
    - name: copy python code
      copy: src=lib/beacon dest=/usr/local/lib/python2.7/dist-packages owner=root group=root
    - name: setup settings dir
      file: path=/etc/beacon state=directory mode=0755 owner=root group=root
    - name: setup positions dir
      file: path=/var/beacon state=directory mode=0755 owner=www-data group=www-data
    - name: copy settings template
      copy: src=conf/settings.yaml dest=/etc/beacon/settings.yaml owner=root group=root
    - name: copy runner
      copy: src=bin/beacon-runner.py dest=/usr/local/bin/beacon owner=root group=root
    - name: copy upstart service definition
      copy: src=conf/upstart.conf dest=/etc/init/beacon.conf owner=root group=root


# vim:ft=ansible:
