---
- hosts: all
  sudo: yes
  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
  tasks:
    - name: copy webapp
      copy: src=webapp/ dest=/var/www/{{fqdn}} owner=www-data group=www-data
    - name: copy webapp vhost conf
      template: src=conf/apache.conf dest=/etc/apache2/sites-available/{{fqdn}}.conf
    - name: enable site
      command: a2ensite {{fqdn}}
      args:
        creates: /etc/apache2/sites-enabled/{{fqdn}}.conf
      notify:
        - restart apache2
    - name: copy python code
      copy: src=lib/beacon dest=/usr/local/lib/python2.7/dist-packages owner=root group=root
    - name: setup settings dir
      file: path=/etc/beacon state=directory mode=0755 owner=root group=root
    - name: setup positions dir
      file: path=/var/beacon state=directory mode=0755 owner=www-data group=www-data
    - name: copy settings template
      copy: src=conf/settings.yaml dest=/etc/beacon/settings.yaml owner=root group=root
    - name: copy runner
      copy: src=bin/beacon-runner.py dest=/usr/local/bin/beacon owner=root group=root
    - name: copy upstart service definition
      copy: src=conf/upstart.conf dest=/etc/init/beacon.conf owner=root group=root


# vim:ft=ansible:
