---
- hosts: all
  sudo: yes
  tasks:
    - name: copy webapp
      copy: src=webapp/ dest=/var/www/{{fqdn}} owner=www-data group=www-data
    - name: copy python code
      copy: src=lib/beacon dest=/usr/local/lib/python2.7/dist-packages owner=root group=root
    - name: setup settings dir
      file: path=/etc/beacon state=directory mode=0755 owner=root group=root
    - name: setup positions dir
      file: path=/var/beacon state=directory mode=0755 owner=www-data group=www-data
    - name: copy settings
      copy: src=conf/settings-template.yaml dest=/etc/beacon/settings-template.yaml owner=root group=root
    - name: copy runners
      copy: src=bin/beacon-runner.py dest=/usr/local/bin/beacon owner=root group=root
    - name: copy upstart service definition
      copy: src=conf/upstart.conf dest=/etc/init/beacon.conf owner=root group=root

# vim:ft=ansible:
