[dev]
127.0.0.1

[dev:vars]
fqdn=gps.gmendiola.com
mail_key=key-1eab42ae67b1e766f58d419a9c8ae5ff
ansible_ssh_port=2222
ansible_ssh_user=vagrant
ansible_ssh_private_key_file=.vagrant/machines/default/virtualbox/private_key
host_key_checking=False
