locations_path: <file specifying locations>
gps_dir: <dir to store position json files>
gps_key: <webapp key for auth>
email_settings:
    from: <from address>
    api_key: <mailgun api key>
interval: <polling interval>
