---
# Copy webapp
- name: copy webapp
  copy: src=../webapp/ dest=/var/www/{{fqdn}} owner=www-data group=www-data
- name: make cgi executable
  file: path={{item}} mode="a+x"
  with_items:
    - /var/www/{{fqdn}}/log.cgi
    - /var/www/{{fqdn}}/report.cgi
- name: copy python code
  copy: src=../lib/beacon dest=/usr/local/lib/python2.7/dist-packages owner=root group=root
- name: setup settings dir
  file: path=/etc/beacon state=directory mode=0755 owner=root group=root
- name: setup positions dir
  file: path=/var/beacon state=directory mode=0755 owner=www-data group=www-data
- name: copy settings template
  copy: src=../conf/settings.yaml dest=/etc/beacon/settings.yaml owner=root group=root


# vim:ft=ansible:
