---
# Enable apache mods
- name: enable apache mods
  apache2_module: state=present name={{ item }}
  with_items:
    - cgid
    - ssl
  notify:
    - restart apache2

# Setup vhost
- name: copy webapp vhost conf
  template: src=../conf/apache.conf dest=/etc/apache2/sites-available/{{fqdn}}.conf
- name: enable site
  command: a2ensite {{fqdn}}.conf
  args:
    creates: /etc/apache2/sites-enabled/{{fqdn}}.conf
  notify:
    - restart apache2

# Copy SSL cert
- name: make ssl dir
  file: path=/etc/apache2/ssl state=directory mode=755 owner=root group=root
- name: copy webapp ssl cert
  copy: src=../ssl/{{fqdn}}.crt dest=/etc/apache2/ssl/{{fqdn}}.crt owner=root group=root
- name: copy webapp ssl key
  copy: src=../ssl/{{fqdn}}.key dest=/etc/apache2/ssl/{{fqdn}}.key owner=root group=root
